### ISSUE TITLE
Assigning a value to $Type causes PSGit in Powerline to not display correctly

### ISSUE THREAD

**Issue by scrthq** [PoshCode/PSGit#55] opened 2017-06-06 14:58 UTC
**Details:** When assigning a value to the variable `$type` in Powershell, PSGit when used in a Powerline custom prompt starts displaying incorrectly. It also intermittently shifts the console output left 1 character, so the first character appears wrapped onto the right side of the console when this happens.

**Occurrence:** This occurs in both Visual Studio Code and standard Powershell console.

**VSCode Issue Replication**
![alt text](http://i.imgur.com/U5dSiG6.png "VSCode Issue Replication")

**Powershell Issue Replication**
![alt text](http://i.imgur.com/GpcNkV1.png "Powershell Issue Replication")

**Environment:** Both Windows 10 Enterprise and Pro, 64-bit

**PSVersionTable:**
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Current PS profile contents:**
```powershell
#requires -Module @{ModuleName="PSGit"; ModuleVersion="2.0.4"}, @{ModuleName="PowerLine"; ModuleVersion="2.0.0"}
using module PowerLine
using namespace PowerLine

$PowerLinePrompt = 1,
    (
        $null, 
        @(
            @{ text = { New-PowerLineBlock (Get-Elapsed) -ErrorBackgroundColor DarkRed -ErrorForegroundColor White -ForegroundColor Black -BackgroundColor DarkGray } }
            @{ bg = "Gray";     fg = "Black"; text = { Get-Date -f "T" } }
        )
    ),  @(
            @{ bg = "Blue";     fg = "Black"; text = { $MyInvocation.HistoryId } }
            @{ bg = "Cyan";     fg = "White"; text = { [PowerLine.Prompt]::Gear * $NestedPromptLevel } }
            @{ bg = "Cyan";     fg = "White"; text = { if($pushd = (Get-Location -Stack).count) { "$([char]187)" + $pushd } } }
            @{ bg = "DarkBlue"; fg = "White"; text = { $pwd.Drive.Name } }
            @{ bg = "DarkBlue"; fg = "White"; text = { Split-Path $pwd -leaf } }
            @{ text = { Get-GitStatusPowerline } }
        )

Set-PowerLinePrompt -CurrentDirectory -PowerlineFont:(!$SafeCharacters) -Title { "PowerShell - {0} ({1})" -f (Convert-Path $pwd),  $pwd.Provider.Name }

Set-GitPromptSettings -SeparatorText '' -BeforeText '' -BeforeChangesText '' -AfterChangesText '' -AfterNoChangesText '' `
                      -BranchText "$([PowerLine.Prompt]::Branch) " -BranchForeground White -BranchBackground Cyan `
                      -BehindByText '?' -BehindByForeground White -BehindByBackground DarkCyan `
                      -AheadByText '?' -AheadByForeground White -AheadByBackground DarkCyan `
                      -StagedChangesForeground White -StagedChangesBackground DarkBlue `
                      -UnStagedChangesForeground White -UnStagedChangesBackground Blue
```

**Comment by Jaykul** [comment] 2017-06-07 06:26
Wow, thanks for tracking down your root cause there ... I'm working on a new version of PowerLine and this bit of PSGit, so I'll make sure this gets fixed too.

**Comment by Jaykul** [comment] 2018-12-11 04:14
This is fixed now.

**Closed as completed by Jaykul** 2018-12-11 04:14 UTC
Labels: bug

**Comment by scrthq** [comment] 2018-12-11 04:51
Awesome, thanks, Joel!
